apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- apm-secret-php-hello-unstable.yaml
- apm-secret-value-add-unstable.yaml
- activemq-secret-backbase-unstable.yaml
- apm-secret-backbase-unstable.yaml
- database-secret-backbase-unstable.yaml
- signature-secret-backbase-unstable.yaml
- splunk-secret-backbase-unstable.yaml
- appdynamics-test-secret-backbase-unstable.yaml
